language: python
python:
  - 2.6
  - 2.7
install:
  - sudo echo "127.0.0.1 localhost" > /etc/hosts
  - sudo apt-get install -y libevent-dev git gcc python-dev sendmail bacula-console
  - cp buildout.d/templates/buildout.cfg.in buildout.cfg
  - sed -i 's/bacula.db/bacula_kaki.db/' buildout.cfg
  - director_password=$(sudo grep 'Password' /etc/bacula/bconsole.conf | sed 's/.*Password\s*=\s*"\(.\+\)"/\1/')
  - sed -i "s@director_password = @director_password = $director_password@" buildout.cfg
  - python bootstrap.py
  - bin/buildout

before_script:
  - "sh -e /etc/init.d/xvfb start"

script:
  - bin/nosetests
#  - find almir/tests/javascript/ -iname "test_*.html" | DISPLAY=:99.0 xargs /usr/local/bin/phantomjs almir/tests/javascript/run-qunit.js
  - DISPLAY=:99.0 phantomjs almir/tests/javascript/run-qunit.js almir/tests/javascript/test_datatables.html

notifications:
  irc:
    - "irc.freenode.org#almir"
