language: python
python:
  - 2.6
  - 2.7
install:
  - sudo apt-get install -y libevent-dev git gcc python-dev bacula
  - cp buildout.d/templates/buildout.cfg.in buildout.cfg
  - python bootstrap.py
  - bin/buildout
script: bin/nosetests

notifications:
  irc:
    - "irc.freenode.org#almir"
